[package]
name = "pep_api_service"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
actix-cors = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yml = "0.0.12"
futures-util = "0.3.30"
env_logger = "0.11.3"
libpep = { git = "https://github.com/JobDoesburg/libpep.git", branch = "dev_paas" }
base64 = "0.22.1"
rand = "^0.8"
rand_core = "^0.6"
redis = "0.27.0"
chrono = "0.4.38"
redis-macros = "0.4.2"
hex = "0.4.3"
jsonwebtoken = {features = ["use_pem"], version = "9.3.0" }
